<a href="https://colab.research.google.com/github/JohnnieJnr/Maching-Learning/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1P9PFwI_A5oafT69fLCK7EqkeqSKkC4nx')

# 5 Simple Torch Operations

The torch package contains data structures for multi-dimensional tensors and mathematical operations over these are defined. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.

- function 1 torch.full
- function 2 torch.rsqrt
- function 3 torch.max
- function 4 torch.neg
- function 5 torch.log10

Before we begin, let's install and import PyTorch

In [17]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [18]:
# Import torch and other required modules
import torch

## Function 1 - torch.full

Concatenete the given tensors with compatible shapes to produce the desired output

In [19]:
t1 = torch.full((4,4), 12)
t1

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]])

The above example shows a tensor with a 4 colums and 4 rows witha a fixed value of 12

In [20]:
t2 = torch.full((4,4), 4)
t2

t3 = torch.cat((t1, t2))
t3

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 4,  4,  4,  4],
        [ 4,  4,  4,  4],
        [ 4,  4,  4,  4],
        [ 4,  4,  4,  4]])

concatenation of two compatible tensors to create a single tensor

In [21]:
t4 = torch.full((3,2), 2.)
t4

torch.cat((t2, t4))

RuntimeError: ignored

The code displayed an error because the both tensors have different sizes ie. t2 has a size of 4 dimensions and t4 has a size of 2 dimension, hence they are incompatible.


To use thhis function, both tensors must have the same dimensions in order for the function to work.

Let's save our work using Jovian before continuing.

In [34]:
!pip install jovian --upgrade --quiet

In [35]:
import jovian

In [ ]:
jovian.commit(project='pytorch-tensor')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: 

## Function 2 - torch.rsqrt

Returns a new tensor with the reciprocal of the square-root of each of the elements of input.

In [22]:
torch.rsqrt(torch.tensor([6., 12, 4]))

tensor([0.4082, 0.2887, 0.5000])

Explanation about example

In [23]:
torch.rsqrt(torch.tensor([12., 2+4, 2*9]))

tensor([0.2887, 0.4082, 0.2357])

rsqrt function with some arithemtic calculation

In [24]:
torch.rsqrt(torch.tensor([2, 4, 34]))

RuntimeError: ignored

The above code displays a runtime error because the tensor.rsqrt function does not work with long dtype.

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 3 - torch.max

Returns the maximum value of all elements in the input tensor.

In [25]:
# Example 1 - working
torch.max(torch.tensor([2., 1, 13, 65, 132, 0, 24]))

tensor(132.)

The above function searches the list and prints the maximum value

In [26]:
# Example 2 - working
torch.max(torch.tensor([2.*9, 7+12, 34/5]))

tensor(19.)

torch.max performing simple arithmetic operation to determine the max vallue and print it out

In [27]:
# Example 3 - breaking (to illustrate when it breaks)
torch.max(torch.tensor(-2, -12, -5))

TypeError: ignored

An error occured here because the arguments were not placen in a square braces [ ].

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 4 - torch.neg

Returns a new tensor with the negative of the elements of input.

In [28]:
# Example 1 - working
torch.neg(torch.tensor([10, 12, 33]))

tensor([-10, -12, -33])

As expected the torch.neg functions prints out the negative value of the inputs

In [29]:
# Example 2 - working
torch.neg(torch.tensor([-12./4, 12*7, 7+-7]))

tensor([  3., -84.,  -0.])

torch.neg performing arithmetic calculation. 

In [30]:
# Example 3 - breaking (to illustrate when it breaks)
torch.neg(torch.tensor([2., *, 12/4, -0]))

SyntaxError: ignored

This error occured because the next value after 2. which * is actually an arithmetic sign and cannot be a value

The function torch.neg is used to convert values to their negative

In [ ]:
jovian.commit(project='01-tensor-operations')

## Function 5 - torch.log10

Returns a new tensor with the logarithm to the base 10 of the elements of input.

In [31]:
# Example 1 - working
torch.log10(torch.tensor([25., 2.]))

tensor([1.3979, 0.3010])

A simple sensor that prints the log10 value of all inputs

In [32]:
# Example 2 - working
torch.log10(torch.tensor([12.*2, 7+6]))

tensor([1.3802, 1.1139])

Simple arithmetic opreration with tensor.log10

In [33]:
# Example 3 - breaking (to illustrate when it breaks)
torch.log10(torch.tensor([12*2, 7+6]))

RuntimeError: ignored

tensor.log10 cannot be implemented using long values, hence the errror.

The tensor.log10 function is used when you want to print the value of inputs in base 10.

In [ ]:
jovian.commit(project='01-tensor-operations')

## Conclusion


In this notebook , I covered 5 simple Math functions(tensor.log10, tensor.neg, tensor.rsqrt, tensor.max and tensor.full) and described thier functions with examples. There are more complex and vast features available in Pytorch which can be explored later on.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations.')